### ISSUE TITLE
Mollie Internal Server Error

### ISSUE THREAD

**Issue by gleichaberanders** [pretix/pretix-mollie#5]
Hey together,

i just implemented the Mollie plugin in our pretix system.
Mollie says the payment is okay, but pretix is unable to get this information. First step: we just select sofort via mollie, we authorize the test payment:

<img width="485" alt="Bildschirmfoto 2019-03-18 um 21 36 01" src="https://user-images.githubusercontent.com/48489114/54562453-50893680-49c7-11e9-99a4-21998de855ae.png">

After that we just get this information / internal server error:
<img width="639" alt="Bildschirmfoto 2019-03-18 um 21 48 40" src="https://user-images.githubusercontent.com/48489114/54562602-a1992a80-49c7-11e9-8973-0496aa1a734e.png">
(URL: https://url.shop/eventname/veranstaltung/mollie/return/HR9AQ/e2c32a748445edd56a5f081daebf84e566b25cac/34/)

If we check Mollie, it says the payment is okay, but there is an web hook error:
<img width="1372" alt="Bildschirmfoto 2019-03-18 um 21 38 27" src="https://user-images.githubusercontent.com/48489114/54562658-b70e5480-49c7-11e9-84db-4a10b1d467f4.png">

If we check the pretix backend, we are not able to see that the order is payed:
<img width="1409" alt="Bildschirmfoto 2019-03-18 um 21 39 38" src="https://user-images.githubusercontent.com/48489114/54562725-ddcc8b00-49c7-11e9-88d1-8adea0da0c09.png">
<img width="1146" alt="Bildschirmfoto 2019-03-18 um 21 39 33" src="https://user-images.githubusercontent.com/48489114/54562704-d311f600-49c7-11e9-9f3a-34d7b6b070ab.png">

**Comment by raphaelm** [comment]
Can you check ``pretix.log`` for the actual error message, please?

**Comment by gleichaberanders** [comment]
Its just in the test system, if we switch it to live - it works :)

**Comment by lesander** [comment]
Hi there @raphaelm, first of all: thanks for your plugin.

I've encountered the same problem @gleichaberanders has encountered. In test mode, using Mollie test keys, I too receive a 500 error.

`pretix.log`:

```
ERROR 2019-10-04 18:41:40,180 django.request log Internal Server Error: /syntax/test-event/mollie/webhook/1/
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/pretix_mollie/views.py", line 150, in handle_payment
    resp.raise_for_status()
  File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 422 Client Error: Unprocessable Entity for url: https://api.mollie.com/v2/payments/tr_K7qgaWBnQp?testmode=true

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/pretix/src/pretix/presale/utils.py", line 158, in wrap
    response = func(request=request, *args, **kwargs)
  File "/pretix/src/pretix/presale/utils.py", line 158, in wrap
    response = func(request=request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/utils/decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pretix_mollie/views.py", line 287, in post
    handle_payment(self.payment, request.POST.get('id'))
  File "/usr/local/lib/python3.6/site-packages/pretix_mollie/views.py", line 206, in handle_payment
    raise PaymentException(_('We had trouble communicating with Mollie. Please try again and get in touch '
pretix.base.payment.PaymentException: We had trouble communicating with Mollie. Please try again and get in touch with us if this problem persists.
```

**Comment by lesander** [comment]
Note: I’m not sure if I used Mollie’s OAuth or API key. Will check later this evening.

**Comment by lesander** [comment]
This seems to occur for both OAuth and API key implementations. For further debugging we'd need to print Mollie's `detail` and `field` strings in the json response body.

https://docs.mollie.com/guides/handling-errors -> <kbd>CTRL</kbd> + <kbd>F</kbd> -> "422"

**Comment by pc-coholic** [comment]
It has been a long time, but I think we might have fixed this in #58.

I'll close this for now; please feel free to reopen if this still persists - 5 years later 😬
